json.id clothing.id
json.name clothing.name
json.price clothing.price
json.is_discounted? clothing.is_discounted?
json.tax clothing.tax
json.total clothing.total 
json.image_url clothing.image_url
json.description clothing.description
json.supplier_id clothing.supplier_id
json.supplier clothing.supplier
json.created_at clothing.created_at
json.updated_at clothing.updated_at
