json.id order.id
json.user order.user
json.clothing order.clothing
json.user_id order.user_id
json.clothing_id order.clothing_id
json.quantity order.quantity
json.subtotal order.subtotal
json.tax order.tax
json.total order.total
json.created_at order.created_at
json.updated_at order.updated_at
